In [66]:
# Pandas: es una biblioteca para acseso y manupulación de datos "simple" de datos 
import pandas as pd

In [67]:
data = pd.read_csv('https://bit.ly/31B56KB')
type(data)
data.head(2)

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
0                 10         70.3       213         582               6.0   
1                 13         61.0        91         132               8.2   

   Lluvia  Dias_Lluvia  
0    7.05           36  
1   48.52          100

In [68]:
data.tail(2)

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
39                 31         55.2        35          71               6.5   
40                 16         45.7       569         717              11.8   

    Lluvia  Dias_Lluvia  
39   40.75          148  
40   29.07          123

In [69]:
data.info()
data.describe()# EDA => AnálisisExploratorio de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Contaminacion_SO2  41 non-null     int64  
 1   Temperatura        41 non-null     float64
 2   Fabricas           41 non-null     int64  
 3   Habitantes         41 non-null     int64  
 4   Velocidad_viento   41 non-null     float64
 5   Lluvia             41 non-null     float64
 6   Dias_Lluvia        41 non-null     int64  
dtypes: float64(3), int64(4)
memory usage: 2.4 KB


Contaminacion_SO2  Temperatura     Fabricas   Habitantes  \
count          41.000000    41.000000    41.000000    41.000000   
mean           30.048780    55.763415   463.097561   608.609756   
std            23.472272     7.227716   563.473948   579.113023   
min             8.000000    43.500000    35.000000    71.000000   
25%            13.000000    50.600000   181.000000   299.000000   
50%            26.000000    54.600000   347.000000   515.000000   
75%            35.000000    59.300000   462.000000   717.000000   
max           110.000000    75.500000  3344.000000  3369.000000   

       Velocidad_viento     Lluvia  Dias_Lluvia  
count         41.000000  41.000000    41.000000  
mean           9.443902  36.769024   113.902439  
std            1.428644  11.771550    26.506419  
min            6.000000   7.050000    36.000000  
25%            8.700000  30.960000   103.000000  
50%            9.300000  38.740000   115.000000  
75%           10.600000  43.110000   128.000000  
max           12.700000  59.800000   166.000000

In [70]:
len(data)

41

In [71]:
data.columns

Index(['Contaminacion_SO2', 'Temperatura', 'Fabricas', 'Habitantes',
       'Velocidad_viento', 'Lluvia', 'Dias_Lluvia'],
      dtype='object')

In [72]:
len(data.columns)

7

In [73]:
data.shape

(41, 7)

In [74]:
data.dtypes

Contaminacion_SO2      int64
Temperatura          float64
Fabricas               int64
Habitantes             int64
Velocidad_viento     float64
Lluvia               float64
Dias_Lluvia            int64
dtype: object

In [75]:
data.values #siempre utilizar arreglos de numpy

array([[  10.  ,   70.3 ,  213.  ,  582.  ,    6.  ,    7.05,   36.  ],
       [  13.  ,   61.  ,   91.  ,  132.  ,    8.2 ,   48.52,  100.  ],
       [  12.  ,   56.7 ,  453.  ,  716.  ,    8.7 ,   20.66,   67.  ],
       [  17.  ,   51.9 ,  454.  ,  515.  ,    9.  ,   12.95,   86.  ],
       [  56.  ,   49.1 ,  412.  ,  158.  ,    9.  ,   43.37,  127.  ],
       [  36.  ,   54.  ,   80.  ,   80.  ,    9.  ,   40.25,  114.  ],
       [  29.  ,   57.3 ,  434.  ,  757.  ,    9.3 ,   38.89,  111.  ],
       [  14.  ,   68.4 ,  136.  ,  529.  ,    8.8 ,   54.47,  116.  ],
       [  10.  ,   75.5 ,  207.  ,  335.  ,    9.  ,   59.8 ,  128.  ],
       [  24.  ,   61.5 ,  368.  ,  497.  ,    9.1 ,   48.34,  115.  ],
       [ 110.  ,   50.6 , 3344.  , 3369.  ,   10.4 ,   34.44,  122.  ],
       [  28.  ,   52.3 ,  361.  ,  746.  ,    9.7 ,   38.74,  121.  ],
       [  17.  ,   49.  ,  104.  ,  201.  ,   11.2 ,   30.85,  103.  ],
       [   8.  ,   56.6 ,  125.  ,  277.  ,   12.7 ,   30.58,   

In [76]:
data.dtypes

Contaminacion_SO2      int64
Temperatura          float64
Fabricas               int64
Habitantes             int64
Velocidad_viento     float64
Lluvia               float64
Dias_Lluvia            int64
dtype: object

In [77]:
# Particiones en DF
data[9:12]

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
9                  24         61.5       368         497               9.1   
10                110         50.6      3344        3369              10.4   
11                 28         52.3       361         746               9.7   

    Lluvia  Dias_Lluvia  
9    48.34          115  
10   34.44          122  
11   38.74          121

In [78]:
data.iloc[7:13, 2:5] # data.iloc [numero de filas , numero de columnas] te ayuda a extraer fials y columnas especiales

Fabricas  Habitantes  Velocidad_viento
7        136         529               8.8
8        207         335               9.0
9        368         497               9.1
10      3344        3369              10.4
11       361         746               9.7
12       104         201              11.2

In [79]:
data.iloc[7:13,:]

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
7                  14         68.4       136         529               8.8   
8                  10         75.5       207         335               9.0   
9                  24         61.5       368         497               9.1   
10                110         50.6      3344        3369              10.4   
11                 28         52.3       361         746               9.7   
12                 17         49.0       104         201              11.2   

    Lluvia  Dias_Lluvia  
7    54.47          116  
8    59.80          128  
9    48.34          115  
10   34.44          122  
11   38.74          121  
12   30.85          103

In [80]:
data.iloc[:,2:6]

Fabricas  Habitantes  Velocidad_viento  Lluvia
0        213         582               6.0    7.05
1         91         132               8.2   48.52
2        453         716               8.7   20.66
3        454         515               9.0   12.95
4        412         158               9.0   43.37
5         80          80               9.0   40.25
6        434         757               9.3   38.89
7        136         529               8.8   54.47
8        207         335               9.0   59.80
9        368         497               9.1   48.34
10      3344        3369              10.4   34.44
11       361         746               9.7   38.74
12       104         201              11.2   30.85
13       125         277              12.7   30.58
14       291         593               8.3   43.11
15       204         361               8.4   56.77
16       625         905               9.6   41.31
17      1064        1513              10.1   30.96
18       699         744              10.6   25.94
19       381         507              10.0   37.00
20       775         622               9.5   35.89
21       181         347              10.9   30.18
22        46         244               8.9    7.77
23        44         116               8.8   33.36
24       391         463              12.4   36.11
25       462         453               7.1   39.04
26      1007         751              10.9   34.99
27       266         540               8.6   37.01
28      1692        1950               9.6   39.93
29       347         520               9.4   36.22
30       343         179              10.6   42.75
31       337         624               9.2   49.10
32       275         448               7.9   46.00
33       641         844              10.9   35.94
34       721        1233              10.8   48.19
35       137         176               8.7   15.17
36        96         308              10.6   44.68
37       197         299               7.6   42.59
38       379         531               9.4   38.79
39        35          71               6.5   40.75
40       569         717              11.8   29.07

In [81]:
data.iloc[:,2:6].values

array([[ 213.  ,  582.  ,    6.  ,    7.05],
       [  91.  ,  132.  ,    8.2 ,   48.52],
       [ 453.  ,  716.  ,    8.7 ,   20.66],
       [ 454.  ,  515.  ,    9.  ,   12.95],
       [ 412.  ,  158.  ,    9.  ,   43.37],
       [  80.  ,   80.  ,    9.  ,   40.25],
       [ 434.  ,  757.  ,    9.3 ,   38.89],
       [ 136.  ,  529.  ,    8.8 ,   54.47],
       [ 207.  ,  335.  ,    9.  ,   59.8 ],
       [ 368.  ,  497.  ,    9.1 ,   48.34],
       [3344.  , 3369.  ,   10.4 ,   34.44],
       [ 361.  ,  746.  ,    9.7 ,   38.74],
       [ 104.  ,  201.  ,   11.2 ,   30.85],
       [ 125.  ,  277.  ,   12.7 ,   30.58],
       [ 291.  ,  593.  ,    8.3 ,   43.11],
       [ 204.  ,  361.  ,    8.4 ,   56.77],
       [ 625.  ,  905.  ,    9.6 ,   41.31],
       [1064.  , 1513.  ,   10.1 ,   30.96],
       [ 699.  ,  744.  ,   10.6 ,   25.94],
       [ 381.  ,  507.  ,   10.  ,   37.  ],
       [ 775.  ,  622.  ,    9.5 ,   35.89],
       [ 181.  ,  347.  ,   10.9 ,   30.18],
       [  

In [82]:
#Filtros
df = data.filter(["Temperatura", "Velocidad_viento", "Dias_Lluvia"], axis = 1)
df.head(5)

Temperatura  Velocidad_viento  Dias_Lluvia
0         70.3               6.0           36
1         61.0               8.2          100
2         56.7               8.7           67
3         51.9               9.0           86
4         49.1               9.0          127

In [83]:
df = data.drop(["Fabricas", "Habitantes"], axis = 1)
df.head(2)

Contaminacion_SO2  Temperatura  Velocidad_viento  Lluvia  Dias_Lluvia
0                 10         70.3               6.0    7.05           36
1                 13         61.0               8.2   48.52          100

In [85]:
s = data.Contaminacion_SO2


In [87]:
type(s)

pandas.core.series.Series

In [88]:
s.head(2)

0    10
1    13
Name: Contaminacion_SO2, dtype: int64

In [90]:
s.describe()

count     41.000000
mean      30.048780
std       23.472272
min        8.000000
25%       13.000000
50%       26.000000
75%       35.000000
max      110.000000
Name: Contaminacion_SO2, dtype: float64

In [91]:
s.unique(), s.value_counts()

(array([ 10,  13,  12,  17,  56,  36,  29,  14,  24, 110,  28,   8,  30,
          9,  47,  35,  11,  46,  23,  65,  26,  69,  61,  94,  18,  31,
         16]),
 Contaminacion_SO2
 10     4
 14     3
 29     3
 28     2
 17     2
 56     2
 9      2
 26     2
 31     2
 11     2
 13     1
 110    1
 24     1
 36     1
 12     1
 47     1
 35     1
 30     1
 8      1
 23     1
 46     1
 69     1
 65     1
 61     1
 94     1
 18     1
 16     1
 Name: count, dtype: int64)

In [95]:
#Agrupamientos

In [102]:
grupo = data.groupby("Contaminacion_SO2")
grupo.mean()
grupo.mean().head(5)

Temperatura  Fabricas  Habitantes  Velocidad_viento  \
Contaminacion_SO2                                                        
8                       56.600     125.0       277.0             12.70   
9                       67.250     422.5       602.5              9.65   
10                      69.075     369.5       693.5              8.75   
11                      51.950     218.5       353.5             10.65   
12                      56.700     453.0       716.0              8.70   

                   Lluvia  Dias_Lluvia  
Contaminacion_SO2                       
8                  30.580         82.0  
9                  46.355         95.5  
10                 41.035         93.0  
11                 21.940        112.0  
12                 20.660         67.0

In [105]:
grupo.sum().head(5)

Temperatura  Fabricas  Habitantes  Velocidad_viento  \
Contaminacion_SO2                                                        
8                         56.6       125         277              12.7   
9                        134.5       845        1205              19.3   
10                       276.3      1478        2774              35.0   
11                       103.9       437         707              21.3   
12                        56.7       453         716               8.7   

                   Lluvia  Dias_Lluvia  
Contaminacion_SO2                       
8                   30.58           82  
9                   92.71          191  
10                 164.14          372  
11                  43.88          224  
12                  20.66           67

In [106]:
suma = grupo.sum()
suma.head(5)

Temperatura  Fabricas  Habitantes  Velocidad_viento  \
Contaminacion_SO2                                                        
8                         56.6       125         277              12.7   
9                        134.5       845        1205              19.3   
10                       276.3      1478        2774              35.0   
11                       103.9       437         707              21.3   
12                        56.7       453         716               8.7   

                   Lluvia  Dias_Lluvia  
Contaminacion_SO2                       
8                   30.58           82  
9                   92.71          191  
10                 164.14          372  
11                  43.88          224  
12                  20.66           67

In [108]:
cond = suma.Temperatura > 70
cond

Contaminacion_SO2
8      False
9       True
10      True
11      True
12     False
13     False
14      True
16     False
17      True
18     False
23     False
24     False
26      True
28      True
29      True
30     False
31      True
35     False
36     False
46     False
47     False
56      True
61     False
65     False
69     False
94     False
110    False
Name: Temperatura, dtype: bool

In [109]:
suma[cond]

Temperatura  Fabricas  Habitantes  Velocidad_viento  \
Contaminacion_SO2                                                        
9                        134.5       845        1205              19.3   
10                       276.3      1478        2774              35.0   
11                       103.9       437         707              21.3   
14                       174.4       698        1383              29.7   
17                       100.9       558         716              20.2   
26                       109.3       463         839              16.2   
28                       103.3       498         922              18.4   
29                       151.9      1512        2032              29.3   
31                       114.5       131         379              17.1   
56                       105.0      1187         780              18.5   

                   Lluvia  Dias_Lluvia  
Contaminacion_SO2                       
9                   92.71          191  
10                 164.14          372  
11                  43.88          224  
14                 121.65          313  
17                  43.80          189  
26                  79.60          249  
28                  53.91          210  
29                 103.62          412  
31                  85.43          264  
56                  79.26          232

In [110]:
suma[cond==False]

Temperatura  Fabricas  Habitantes  Velocidad_viento  \
Contaminacion_SO2                                                        
8                         56.6       125         277              12.7   
12                        56.7       453         716               8.7   
13                        61.0        91         132               8.2   
16                        45.7       569         717              11.8   
18                        59.4       275         448               7.9   
23                        54.0       462         453               7.1   
24                        61.5       368         497               9.1   
30                        55.6       291         593               8.3   
35                        49.9      1064        1513              10.1   
36                        54.0        80          80               9.0   
46                        47.6        44         116               8.8   
47                        55.0       625         905               9.6   
61                        50.4       347         520               9.4   
65                        49.7      1007         751              10.9   
69                        54.6      1692        1950               9.6   
94                        50.0       343         179              10.6   
110                       50.6      3344        3369              10.4   

                   Lluvia  Dias_Lluvia  
Contaminacion_SO2                       
8                   30.58           82  
12                  20.66           67  
13                  48.52          100  
16                  29.07          123  
18                  46.00          119  
23                  39.04          132  
24                  48.34          115  
30                  43.11          123  
35                  30.96          129  
36                  40.25          114  
46                  33.36          135  
47                  41.31          111  
61                  36.22          147  
65                  34.99          155  
69                  39.93          115  
94                  42.75          125  
110                 34.44          122

In [ ]:
# Numpy: Bliblioteca para procesar arreglos "a la matlab"

In [1]:
import numpy as np

In [1]:
import numpy as np

In [2]:
#Vectores (arreglos unidim)

In [3]:
v = np.array([1,2,3,4,5])
type(v), v.shape, v.ndim, v.dtype

(numpy.ndarray, (5,), 1, dtype('int64'))

In [4]:
v+v, 5.1*v

(array([ 2,  4,  6,  8, 10]), array([ 5.1, 10.2, 15.3, 20.4, 25.5]))

In [5]:
v*v, v@v # @ => producto punto

(array([ 1,  4,  9, 16, 25]), np.int64(55))

In [6]:
m = np.array([[1,2,3],[4, 5, 6],[7, 8, 9]])
m.shape, m.ndim , m.dtype

((3, 3), 2, dtype('int64'))

In [7]:
m+m, 9.9*m

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[ 9.9, 19.8, 29.7],
        [39.6, 49.5, 59.4],
        [69.3, 79.2, 89.1]]))

In [8]:
m*m, m@m # @ Multiplicación matricial convencional

(array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]),
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]]))

In [9]:
np.array([0]*10), np.zeros(10)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [10]:
a =np.zeros(10)
a.shape

(10,)

In [11]:
a.reshape(5,2)


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a = a.reshape(5,2) # se necesita guardar
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
a.resize(1, 10)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
mr = np.random.random((4,5))*10
mr

array([[6.78048206, 0.08086793, 3.89170492, 9.34224047, 9.00672432],
       [1.73825686, 7.6245661 , 1.42093393, 1.63250619, 8.94422635],
       [9.81715866, 4.24547272, 6.34990639, 2.21054308, 2.33752558],
       [8.32281683, 3.32675146, 8.83369328, 4.0102966 , 7.33582324]])

In [17]:
mr[1,4]

np.float64(8.94422634761128)

In [18]:
mr[1,:]

array([1.73825686, 7.6245661 , 1.42093393, 1.63250619, 8.94422635])

In [19]:
mr[:,3]

array([9.34224047, 1.63250619, 2.21054308, 4.0102966 ])

In [20]:
mr[2:4, 1:3]

array([[4.24547272, 6.34990639],
       [3.32675146, 8.83369328]])

In [21]:
mr > 5

array([[ True, False, False,  True,  True],
       [False,  True, False, False,  True],
       [ True, False,  True, False, False],
       [ True, False,  True, False,  True]])

In [22]:
mr[mr > 5]

array([6.78048206, 9.34224047, 9.00672432, 7.6245661 , 8.94422635,
       9.81715866, 6.34990639, 8.32281683, 8.83369328, 7.33582324])

In [23]:
mr.sum()

np.float64(107.25249697470491)

In [24]:
mr.sum(axis=0)#suma por filas

array([26.65871442, 15.27765822, 20.49623852, 17.19558634, 27.62429948])

In [25]:
mr.sum(axis=1) #suma por columnas

array([29.1020197 , 21.36048942, 24.96060643, 31.82938142])

In [26]:
mr.mean(), mr.mean(axis=0), mr.mean(axis=1)

(np.float64(5.362624848735246),
 array([6.6646786 , 3.81941455, 5.12405963, 4.29889658, 6.90607487]),
 array([5.82040394, 4.27209788, 4.99212129, 6.36587628]))

In [27]:
#operaciones Vectorizadas

In [33]:
v + m

ValueError: operands could not be broadcast together with shapes (5,) (3,3) 

In [34]:
v * m 

ValueError: operands could not be broadcast together with shapes (5,) (3,3) 